on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      SRC_PACKAGE_DIR: src/
    steps:
      - uses: mikeal/merge-release@v4.0.7
        name: Automated releases for npm packages.
